[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["soft_legged_robot_env"]

[project]
name = "soft_legged_robot_env"
version = "0.0.1"
dependencies = [
  "gymnasium",
  "numpy",  
]
