from soft_legged_robot_env.wrappers.clip_reward import ClipReward
from soft_legged_robot_env.wrappers.discrete_actions import DiscreteActions
from soft_legged_robot_env.wrappers.reacher_weighted_reward import ReacherRewardWrapper
from soft_legged_robot_env.wrappers.relative_position import RelativePosition
